web:
  url: hhttps://accounts-uat.easywebinar.com/login
  browser: chromium
  headless: false

credentials:
  username: easywebinar4@gmail.com
  password: Uday@63121
  
urls:
  dashboard: https://test-v2.easywebinar.com/v2/events